%YAML 1.2
---
name:
id:

settings:
  position: [-11111, 0, 0]
  velocity:
  orientation:
  angular_rates:
  mass:
  agent_id:
  thermal:
  tf:
  file_path:
  max_vel:
  scale: 0.01
  
sensors:
  CameraSensor:
    type: "eo_camera"
    config_path: "config\\sensors\\basic_eo_camear.yaml"
    model: ".\\assets\\Agents\\Drone E58\\Drone E58.obj"
sound:
animation:
model: ".\\assets\\Agents\\Generic Quadcopter Drone.obj"